// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod dpyc {
        pub mod crypto {
            /// Native-crypto primitives the WASI CPython component cannot provide itself
            /// (secp256k1, AES). Kept low-level: the Python stubs (coincurve, cryptography)
            /// adapt the wheel's calls onto these; key derivation (HKDF) stays pure-Python.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod ops {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_ecdh_nip04_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let len1 = arg3;
                    let result2 = T::ecdh_nip04(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let vec4 = (e).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_ecdh_nip04<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_xonly_pubkey_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result1 = T::xonly_pubkey(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let vec3 = (e).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_xonly_pubkey<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_schnorr_verify_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let len1 = arg3;
                    let len2 = arg5;
                    let result3 = T::schnorr_verify(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
                        _rt::Vec::from_raw_parts(arg4.cast(), len2, len2),
                    );
                    match result3 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_aes256_cbc_decrypt_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let len1 = arg3;
                    let len2 = arg5;
                    let result3 = T::aes256_cbc_decrypt(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
                        _rt::Vec::from_raw_parts(arg4.cast(), len2, len2),
                    );
                    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result3 {
                        Ok(e) => {
                            *ptr4.add(0).cast::<u8>() = (0i32) as u8;
                            let vec5 = (e).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr4
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr4
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                        Err(e) => {
                            *ptr4.add(0).cast::<u8>() = (1i32) as u8;
                            let vec6 = (e.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr4
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr4
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                    };
                    ptr4
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_aes256_cbc_decrypt<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_aes256_cbc_encrypt_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let len1 = arg3;
                    let len2 = arg5;
                    let result3 = T::aes256_cbc_encrypt(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
                        _rt::Vec::from_raw_parts(arg4.cast(), len2, len2),
                    );
                    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result3 {
                        Ok(e) => {
                            *ptr4.add(0).cast::<u8>() = (0i32) as u8;
                            let vec5 = (e).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr4
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr4
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                        Err(e) => {
                            *ptr4.add(0).cast::<u8>() = (1i32) as u8;
                            let vec6 = (e.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr4
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr4
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                    };
                    ptr4
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_aes256_cbc_encrypt<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_aes256_gcm_decrypt_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let len1 = arg3;
                    let len2 = arg5;
                    let len3 = arg7;
                    let result4 = T::aes256_gcm_decrypt(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
                        _rt::Vec::from_raw_parts(arg4.cast(), len2, len2),
                        _rt::Vec::from_raw_parts(arg6.cast(), len3, len3),
                    );
                    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result4 {
                        Ok(e) => {
                            *ptr5.add(0).cast::<u8>() = (0i32) as u8;
                            let vec6 = (e).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr5
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr5
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                        Err(e) => {
                            *ptr5.add(0).cast::<u8>() = (1i32) as u8;
                            let vec7 = (e.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr5
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr5
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                        }
                    };
                    ptr5
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_aes256_gcm_decrypt<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_aes256_gcm_encrypt_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let len1 = arg3;
                    let len2 = arg5;
                    let len3 = arg7;
                    let result4 = T::aes256_gcm_encrypt(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
                        _rt::Vec::from_raw_parts(arg4.cast(), len2, len2),
                        _rt::Vec::from_raw_parts(arg6.cast(), len3, len3),
                    );
                    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result4 {
                        Ok(e) => {
                            *ptr5.add(0).cast::<u8>() = (0i32) as u8;
                            let vec6 = (e).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr5
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr5
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                        Err(e) => {
                            *ptr5.add(0).cast::<u8>() = (1i32) as u8;
                            let vec7 = (e.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr5
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr5
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                        }
                    };
                    ptr5
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_aes256_gcm_encrypt<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// NIP-04 ECDH shared secret: X-coordinate of privkey * (0x02||pubkey-xonly).
                    /// Returns the raw 32-byte X (NIP-04 uses it directly as the AES-256 key).
                    fn ecdh_nip04(
                        privkey: _rt::Vec<u8>,
                        pubkey_xonly: _rt::Vec<u8>,
                    ) -> Result<_rt::Vec<u8>, _rt::String>;
                    /// x-only (32-byte) public key from a 32-byte secret key.
                    fn xonly_pubkey(
                        privkey: _rt::Vec<u8>,
                    ) -> Result<_rt::Vec<u8>, _rt::String>;
                    /// BIP-340 schnorr verify (Nostr): msg is the 32-byte event id.
                    fn schnorr_verify(
                        msg: _rt::Vec<u8>,
                        sig: _rt::Vec<u8>,
                        pubkey_xonly: _rt::Vec<u8>,
                    ) -> bool;
                    /// AES-256-CBC with PKCS7 (NIP-04 payload).
                    fn aes256_cbc_decrypt(
                        key: _rt::Vec<u8>,
                        iv: _rt::Vec<u8>,
                        ciphertext: _rt::Vec<u8>,
                    ) -> Result<_rt::Vec<u8>, _rt::String>;
                    fn aes256_cbc_encrypt(
                        key: _rt::Vec<u8>,
                        iv: _rt::Vec<u8>,
                        plaintext: _rt::Vec<u8>,
                    ) -> Result<_rt::Vec<u8>, _rt::String>;
                    /// AES-256-GCM (vault rows). ciphertext is raw ct||tag; nonce 12 bytes; aad may be empty.
                    fn aes256_gcm_decrypt(
                        key: _rt::Vec<u8>,
                        nonce: _rt::Vec<u8>,
                        aad: _rt::Vec<u8>,
                        ciphertext: _rt::Vec<u8>,
                    ) -> Result<_rt::Vec<u8>, _rt::String>;
                    fn aes256_gcm_encrypt(
                        key: _rt::Vec<u8>,
                        nonce: _rt::Vec<u8>,
                        aad: _rt::Vec<u8>,
                        plaintext: _rt::Vec<u8>,
                    ) -> Result<_rt::Vec<u8>, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_dpyc_crypto_ops_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "dpyc:crypto/ops@0.1.0#ecdh-nip04")] unsafe extern "C" fn
                        export_ecdh_nip04(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8,
                        arg3 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_ecdh_nip04_cabi::<$ty > (arg0, arg1, arg2, arg3) } }
                        #[unsafe (export_name =
                        "cabi_post_dpyc:crypto/ops@0.1.0#ecdh-nip04")] unsafe extern "C"
                        fn _post_return_ecdh_nip04(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_ecdh_nip04::<$ty > (arg0) } }
                        #[unsafe (export_name = "dpyc:crypto/ops@0.1.0#xonly-pubkey")]
                        unsafe extern "C" fn export_xonly_pubkey(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_xonly_pubkey_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name = "cabi_post_dpyc:crypto/ops@0.1.0#xonly-pubkey")]
                        unsafe extern "C" fn _post_return_xonly_pubkey(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_xonly_pubkey::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "dpyc:crypto/ops@0.1.0#schnorr-verify")] unsafe extern "C" fn
                        export_schnorr_verify(arg0 : * mut u8, arg1 : usize, arg2 : * mut
                        u8, arg3 : usize, arg4 : * mut u8, arg5 : usize,) -> i32 { unsafe
                        { $($path_to_types)*:: _export_schnorr_verify_cabi::<$ty > (arg0,
                        arg1, arg2, arg3, arg4, arg5) } } #[unsafe (export_name =
                        "dpyc:crypto/ops@0.1.0#aes256-cbc-decrypt")] unsafe extern "C" fn
                        export_aes256_cbc_decrypt(arg0 : * mut u8, arg1 : usize, arg2 : *
                        mut u8, arg3 : usize, arg4 : * mut u8, arg5 : usize,) -> * mut u8
                        { unsafe { $($path_to_types)*::
                        _export_aes256_cbc_decrypt_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5) } } #[unsafe (export_name =
                        "cabi_post_dpyc:crypto/ops@0.1.0#aes256-cbc-decrypt")] unsafe
                        extern "C" fn _post_return_aes256_cbc_decrypt(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_aes256_cbc_decrypt::<$ty > (arg0) } } #[unsafe
                        (export_name = "dpyc:crypto/ops@0.1.0#aes256-cbc-encrypt")]
                        unsafe extern "C" fn export_aes256_cbc_encrypt(arg0 : * mut u8,
                        arg1 : usize, arg2 : * mut u8, arg3 : usize, arg4 : * mut u8,
                        arg5 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_aes256_cbc_encrypt_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5) } } #[unsafe (export_name =
                        "cabi_post_dpyc:crypto/ops@0.1.0#aes256-cbc-encrypt")] unsafe
                        extern "C" fn _post_return_aes256_cbc_encrypt(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_aes256_cbc_encrypt::<$ty > (arg0) } } #[unsafe
                        (export_name = "dpyc:crypto/ops@0.1.0#aes256-gcm-decrypt")]
                        unsafe extern "C" fn export_aes256_gcm_decrypt(arg0 : * mut u8,
                        arg1 : usize, arg2 : * mut u8, arg3 : usize, arg4 : * mut u8,
                        arg5 : usize, arg6 : * mut u8, arg7 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*::
                        _export_aes256_gcm_decrypt_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7) } } #[unsafe (export_name =
                        "cabi_post_dpyc:crypto/ops@0.1.0#aes256-gcm-decrypt")] unsafe
                        extern "C" fn _post_return_aes256_gcm_decrypt(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_aes256_gcm_decrypt::<$ty > (arg0) } } #[unsafe
                        (export_name = "dpyc:crypto/ops@0.1.0#aes256-gcm-encrypt")]
                        unsafe extern "C" fn export_aes256_gcm_encrypt(arg0 : * mut u8,
                        arg1 : usize, arg2 : * mut u8, arg3 : usize, arg4 : * mut u8,
                        arg5 : usize, arg6 : * mut u8, arg7 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*::
                        _export_aes256_gcm_encrypt_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7) } } #[unsafe (export_name =
                        "cabi_post_dpyc:crypto/ops@0.1.0#aes256-gcm-encrypt")] unsafe
                        extern "C" fn _post_return_aes256_gcm_encrypt(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_aes256_gcm_encrypt::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_dpyc_crypto_ops_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_crypto_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::dpyc::crypto::ops::__export_dpyc_crypto_ops_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::dpyc::crypto::ops);
    };
}
#[doc(inline)]
pub(crate) use __export_crypto_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:dpyc:crypto@0.1.0:crypto:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 530] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x95\x03\x01A\x02\x01\
A\x02\x01B\x10\x01p}\x01j\x01\0\x01s\x01@\x02\x07privkey\0\x0cpubkey-xonly\0\0\x01\
\x04\0\x0aecdh-nip04\x01\x02\x01@\x01\x07privkey\0\0\x01\x04\0\x0cxonly-pubkey\x01\
\x03\x01@\x03\x03msg\0\x03sig\0\x0cpubkey-xonly\0\0\x7f\x04\0\x0eschnorr-verify\x01\
\x04\x01@\x03\x03key\0\x02iv\0\x0aciphertext\0\0\x01\x04\0\x12aes256-cbc-decrypt\
\x01\x05\x01@\x03\x03key\0\x02iv\0\x09plaintext\0\0\x01\x04\0\x12aes256-cbc-encr\
ypt\x01\x06\x01@\x04\x03key\0\x05nonce\0\x03aad\0\x0aciphertext\0\0\x01\x04\0\x12\
aes256-gcm-decrypt\x01\x07\x01@\x04\x03key\0\x05nonce\0\x03aad\0\x09plaintext\0\0\
\x01\x04\0\x12aes256-gcm-encrypt\x01\x08\x04\0\x15dpyc:crypto/ops@0.1.0\x05\0\x04\
\0\x18dpyc:crypto/crypto@0.1.0\x04\0\x0b\x0c\x01\0\x06crypto\x03\0\0\0G\x09produ\
cers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x06\
0.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
