//! Pure crypto primitives — no WIT/wasm dependencies, fully native-testable.
//!
//! Correctness is validated against ground-truth vectors generated by the
//! tollbooth-dpyc wheel (coincurve + cryptography), so these byte-for-byte
//! match what the wheel produces/consumes.

use aes::Aes256;
use aes_gcm::aead::{Aead, KeyInit, Payload};
use aes_gcm::{Aes256Gcm, Key, Nonce};
use cbc::{Decryptor as CbcDec, Encryptor as CbcEnc};
use chacha20::cipher::{KeyIvInit as _, StreamCipher as _};
use chacha20::ChaCha20;
use cipher::block_padding::Pkcs7;
use cipher::{BlockDecryptMut, BlockEncryptMut, KeyIvInit};
use k256::ecdh::diffie_hellman;
use k256::elliptic_curve::sec1::ToEncodedPoint;
use k256::schnorr::{Signature, SigningKey, VerifyingKey};
use k256::{PublicKey, SecretKey};

type R = Result<Vec<u8>, String>;

fn e<T: core::fmt::Display>(x: T) -> String {
    x.to_string()
}

/// NIP-04 ECDH: X-coordinate of privkey * (0x02 || pubkey_xonly), raw 32 bytes.
pub fn ecdh_nip04(privkey: &[u8], pubkey_xonly: &[u8]) -> R {
    if pubkey_xonly.len() != 32 {
        return Err("pubkey_xonly must be 32 bytes".into());
    }
    let sk = SecretKey::from_slice(privkey).map_err(e)?;
    let mut sec1 = [0u8; 33];
    sec1[0] = 0x02; // NIP-04 convention: assume even Y
    sec1[1..].copy_from_slice(pubkey_xonly);
    let pk = PublicKey::from_sec1_bytes(&sec1).map_err(e)?;
    let shared = diffie_hellman(sk.to_nonzero_scalar(), pk.as_affine());
    Ok(shared.raw_secret_bytes().to_vec())
}

/// x-only (32-byte) public key from a 32-byte secret key.
pub fn xonly_pubkey(privkey: &[u8]) -> R {
    let sk = SecretKey::from_slice(privkey).map_err(e)?;
    let ep = sk.public_key().to_encoded_point(true); // 33-byte compressed
    Ok(ep.as_bytes()[1..].to_vec())
}

/// BIP-340 schnorr verify; `msg` is the 32-byte Nostr event id.
pub fn schnorr_verify(msg: &[u8], sig: &[u8], pubkey_xonly: &[u8]) -> bool {
    let vk = match VerifyingKey::from_bytes(pubkey_xonly) {
        Ok(v) => v,
        Err(_err) => {
            #[cfg(test)]
            eprintln!("from_bytes failed: {_err}");
            return false;
        }
    };
    let sig = match Signature::try_from(sig) {
        Ok(s) => s,
        Err(_err) => {
            #[cfg(test)]
            eprintln!("sig try_from failed: {_err}");
            return false;
        }
    };
    // Nostr signs the 32-byte event id DIRECTLY. k256's `verify()` would
    // SHA-256 the message first (BIP-340 message-hashing form); `verify_raw`
    // uses the message as-is, which is what Nostr requires.
    vk.verify_raw(msg, &sig).is_ok()
}

/// BIP-340 schnorr sign (Nostr): `msg` is the 32-byte event id, signed raw (no
/// pre-hashing), matching `schnorr_verify`'s `verify_raw`. Deterministic aux_rand
/// (zeros) — valid per BIP-340; each Nostr event id is unique, so the per-message
/// nonce is unique without an RNG (which the Wasm crypto component lacks).
pub fn schnorr_sign(msg: &[u8], privkey: &[u8]) -> R {
    let sk = SigningKey::from_bytes(privkey).map_err(e)?;
    let sig = sk.sign_raw(msg, &[0u8; 32]).map_err(e)?;
    Ok(sig.to_bytes().to_vec())
}

/// Raw ChaCha20 (RFC 8439) keystream XOR for NIP-44v2. `nonce` is the 12-byte
/// IETF nonce with the block counter starting at 0 — matching what NIP-44 feeds
/// `cryptography`'s ChaCha20 as `[0u8;4] || nonce`. Encrypt and decrypt are the
/// same operation (stream XOR).
pub fn chacha20(key: &[u8], nonce: &[u8], data: &[u8]) -> R {
    let mut cipher = ChaCha20::new_from_slices(key, nonce).map_err(e)?;
    let mut buf = data.to_vec();
    cipher.apply_keystream(&mut buf);
    Ok(buf)
}

pub fn aes256_cbc_decrypt(key: &[u8], iv: &[u8], ct: &[u8]) -> R {
    let dec = CbcDec::<Aes256>::new_from_slices(key, iv).map_err(e)?;
    dec.decrypt_padded_vec_mut::<Pkcs7>(ct).map_err(e)
}

pub fn aes256_cbc_encrypt(key: &[u8], iv: &[u8], pt: &[u8]) -> R {
    let enc = CbcEnc::<Aes256>::new_from_slices(key, iv).map_err(e)?;
    Ok(enc.encrypt_padded_vec_mut::<Pkcs7>(pt))
}

pub fn aes256_gcm_decrypt(key: &[u8], nonce: &[u8], aad: &[u8], ct: &[u8]) -> R {
    if key.len() != 32 {
        return Err("key must be 32 bytes".into());
    }
    if nonce.len() != 12 {
        return Err("nonce must be 12 bytes".into());
    }
    let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(key));
    cipher
        .decrypt(Nonce::from_slice(nonce), Payload { msg: ct, aad })
        .map_err(e)
}

pub fn aes256_gcm_encrypt(key: &[u8], nonce: &[u8], aad: &[u8], pt: &[u8]) -> R {
    if key.len() != 32 {
        return Err("key must be 32 bytes".into());
    }
    if nonce.len() != 12 {
        return Err("nonce must be 12 bytes".into());
    }
    let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(key));
    cipher
        .encrypt(Nonce::from_slice(nonce), Payload { msg: pt, aad })
        .map_err(e)
}
